trigger:
- main       #LIST       # Runs when changes are pushed to the 'main' branch
- master
- devops

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted Ubuntu agent

steps:
- script: mvn test
  displayName: 'Run Maven Tests'

- script: mvn versions:set -DnewVersion=1.1.$(Build.Timestamp)-SNAPSHOT
  displayName: 'Set dynamic version'

- script: mvn package
  displayName: 'Generate build package/Artifact'
  env:
    MAVEN_OPTS: -DskipTests=true

- script: mvn install
  displayName: 'copy the artifact to local maven repository'
  env:
    MAVEN_OPTS: -DskipTests=true

- task: CopyFiles@2
  inputs:
    #SourceFolder: '/home/vsts/work/1/s/webapp/target'  # Adjust the path to your build output
    Contents: '**/*.war'  # Adjust the pattern to match your build artifacts
    TargetFolder: '$(Build.ArtifactStagingDirectory)' #'$(Build.ArtifactStagingDirectory)'  #c:\agent_work\1\a.

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
